
https://github.com/Tyro10000 | Tmcelrat@kent.edu | 216-333-3958

Objective

I have been intrigued with software Development since my first video game. I found working with code to be second nature and no longer wish to be the viewer but the builder.

Skills

HTML	Javascript	JQuery
PHP/CakePHP	C#/C++	SQL
MVC	Bootstrap	Version control(Git)

Experience

PROGRAMMER AVATAR FLEET
2016
Helped In the software development cycle of software products
Planned new additions to software package
Developed additional functionality for product.
Assisted with scrum process for developing software product.

TECH SUPPORT KENT STATE UNIVERSITY
2015-2017
Troubleshot small software and hardware problems, reset user’s accounts.
Provided blackboard learn support to students
Helped user’s university software issues.
Answered General questions about campus and events

IS SERVER INTERN KENT STATE UNIVERSITY
2017+
Installed OS on machines via disk and USB Stick
Research into new networking and administrative software
Documentation of systems

School

KENT STATE UNIVERSITY KENT, OHIO
COMPUTER SCIENCE
GPA 3.1

Leadership
President of Stem Scholars 2015-2017
Robotics team 2010-2013
REFERENCES	NICOLAS ZEVCHEK
KENT STATE UNIVERSITY
330-672-0041
